spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://choizeus-db.${DB_URL}.us-east-2.rds.amazonaws.com:3306/moodmate?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}


jwt:
  secret: ${JWT_KEY}
  expiration_time: 180